/// Litany of Loreto (Litany of the Blessed Virgin Mary)
/// Prayed after the Rosary as is traditional
class LitanyOfLoreto {
  static const invocations = {
    'en': [
      // Lord, have mercy / Christ, have mercy
      'Lord, have mercy on us.',
      'Christ, have mercy on us.',
      'Lord, have mercy on us.',
      'Christ, hear us.',
      'Christ, graciously hear us.',
      // God the Father...
      'God, the Father of Heaven, have mercy on us.',
      'God the Son, Redeemer of the world, have mercy on us.',
      'God, the Holy Spirit, have mercy on us.',
      'Holy Trinity, One God, have mercy on us.',
      // Holy Mary...
      'Holy Mary, pray for us.',
      'Holy Mother of God, pray for us.',
      'Holy Virgin of virgins, pray for us.',
      'Mother of Christ, pray for us.',
      'Mother of divine grace, pray for us.',
      'Mother most pure, pray for us.',
      'Mother most chaste, pray for us.',
      'Mother inviolate, pray for us.',
      'Mother undefiled, pray for us.',
      'Mother most amiable, pray for us.',
      'Mother most admirable, pray for us.',
      'Mother of good counsel, pray for us.',
      'Mother of our Creator, pray for us.',
      'Mother of our Savior, pray for us.',
      'Virgin most prudent, pray for us.',
      'Virgin most venerable, pray for us.',
      'Virgin most renowned, pray for us.',
      'Virgin most powerful, pray for us.',
      'Virgin most merciful, pray for us.',
      'Virgin most faithful, pray for us.',
      'Mirror of justice, pray for us.',
      'Seat of wisdom, pray for us.',
      'Cause of our joy, pray for us.',
      'Spiritual vessel, pray for us.',
      'Vessel of honor, pray for us.',
      'Singular vessel of devotion, pray for us.',
      'Mystical rose, pray for us.',
      'Tower of David, pray for us.',
      'Tower of ivory, pray for us.',
      'House of gold, pray for us.',
      'Ark of the covenant, pray for us.',
      'Gate of heaven, pray for us.',
      'Morning star, pray for us.',
      'Health of the sick, pray for us.',
      'Refuge of sinners, pray for us.',
      'Comforter of the afflicted, pray for us.',
      'Help of Christians, pray for us.',
      'Queen of angels, pray for us.',
      'Queen of patriarchs, pray for us.',
      'Queen of prophets, pray for us.',
      'Queen of apostles, pray for us.',
      'Queen of martyrs, pray for us.',
      'Queen of confessors, pray for us.',
      'Queen of virgins, pray for us.',
      'Queen of all saints, pray for us.',
      'Queen conceived without original sin, pray for us.',
      'Queen assumed into heaven, pray for us.',
      'Queen of the most holy Rosary, pray for us.',
      'Queen of peace, pray for us.',
      // Closing
      'Lamb of God, who takest away the sins of the world, spare us, O Lord.',
      'Lamb of God, who takest away the sins of the world, graciously hear us, O Lord.',
      'Lamb of God, who takest away the sins of the world, have mercy on us.',
    ],
    'la': [
      'Dómine, miserére nobis.',
      'Christe, miserére nobis.',
      'Dómine, miserére nobis.',
      'Christe, audi nos.',
      'Christe, exáudi nos.',
      'Pater de cælis, Deus, miserére nobis.',
      'Fili, Redémptor mundi, Deus, miserére nobis.',
      'Spíritus Sancte, Deus, miserére nobis.',
      'Sancta Trínitas, unus Deus, miserére nobis.',
      'Sancta María, ora pro nobis.',
      'Sancta Dei Génitrix, ora pro nobis.',
      'Sancta Virgo vírginum, ora pro nobis.',
      'Mater Christi, ora pro nobis.',
      'Mater divínæ grátiæ, ora pro nobis.',
      'Mater puríssima, ora pro nobis.',
      'Mater castíssima, ora pro nobis.',
      'Mater invioláta, ora pro nobis.',
      'Mater intemeráta, ora pro nobis.',
      'Mater amábilis, ora pro nobis.',
      'Mater admirábilis, ora pro nobis.',
      'Mater boni consílii, ora pro nobis.',
      'Mater Creatóris, ora pro nobis.',
      'Mater Salvatóris, ora pro nobis.',
      'Virgo prudentíssima, ora pro nobis.',
      'Virgo veneránda, ora pro nobis.',
      'Virgo prædicánda, ora pro nobis.',
      'Virgo potens, ora pro nobis.',
      'Virgo clemens, ora pro nobis.',
      'Virgo fidélis, ora pro nobis.',
      'Spéculum iustítiæ, ora pro nobis.',
      'Sedes sapiéntiæ, ora pro nobis.',
      'Causa nostræ lætítiæ, ora pro nobis.',
      'Vas spiritále, ora pro nobis.',
      'Vas honorábile, ora pro nobis.',
      'Vas insígne devotiónis, ora pro nobis.',
      'Rosa mýstica, ora pro nobis.',
      'Turris Davídica, ora pro nobis.',
      'Turris ebúrnea, ora pro nobis.',
      'Domus áurea, ora pro nobis.',
      'Fœderis arca, ora pro nobis.',
      'Iánua cæli, ora pro nobis.',
      'Stella matutína, ora pro nobis.',
      'Salus infirmórum, ora pro nobis.',
      'Refúgium peccatórum, ora pro nobis.',
      'Solácium afflictórum, ora pro nobis.',
      'Auxílium Christianórum, ora pro nobis.',
      'Regína Angelórum, ora pro nobis.',
      'Regína Patriarchárum, ora pro nobis.',
      'Regína Prophetárum, ora pro nobis.',
      'Regína Apostolórum, ora pro nobis.',
      'Regína Mártyrum, ora pro nobis.',
      'Regína Confessórum, ora pro nobis.',
      'Regína Vírginum, ora pro nobis.',
      'Regína Sanctórum ómnium, ora pro nobis.',
      'Regína sine labe origináli concépta, ora pro nobis.',
      'Regína in cælum assúmpta, ora pro nobis.',
      'Regína sacratíssimi Rosárii, ora pro nobis.',
      'Regína pacis, ora pro nobis.',
      'Agnus Dei, qui tollis peccáta mundi, parce nobis, Dómine.',
      'Agnus Dei, qui tollis peccáta mundi, exáudi nos, Dómine.',
      'Agnus Dei, qui tollis peccáta mundi, miserére nobis.',
    ],
    'es': [
      'Señor, ten piedad de nosotros.',
      'Cristo, ten piedad de nosotros.',
      'Señor, ten piedad de nosotros.',
      'Cristo, óyenos.',
      'Cristo, escúchanos.',
      'Dios Padre celestial, ten piedad de nosotros.',
      'Dios Hijo, Redentor del mundo, ten piedad de nosotros.',
      'Dios Espíritu Santo, ten piedad de nosotros.',
      'Santísima Trinidad, un solo Dios, ten piedad de nosotros.',
      'Santa María, ruega por nosotros.',
      'Santa Madre de Dios, ruega por nosotros.',
      'Santa Virgen de las vírgenes, ruega por nosotros.',
      'Madre de Cristo, ruega por nosotros.',
      'Madre de la divina gracia, ruega por nosotros.',
      'Madre purísima, ruega por nosotros.',
      'Madre castísima, ruega por nosotros.',
      'Madre inviolable, ruega por nosotros.',
      'Madre inmaculada, ruega por nosotros.',
      'Madre amable, ruega por nosotros.',
      'Madre admirable, ruega por nosotros.',
      'Madre del buen consejo, ruega por nosotros.',
      'Madre del Creador, ruega por nosotros.',
      'Madre del Salvador, ruega por nosotros.',
      'Virgen prudentísima, ruega por nosotros.',
      'Virgen venerable, ruega por nosotros.',
      'Virgen digna de alabanza, ruega por nosotros.',
      'Virgen poderosa, ruega por nosotros.',
      'Virgen clemente, ruega por nosotros.',
      'Virgen fiel, ruega por nosotros.',
      'Espejo de justicia, ruega por nosotros.',
      'Trono de sabiduría, ruega por nosotros.',
      'Causa de nuestra alegría, ruega por nosotros.',
      'Vaso espiritual, ruega por nosotros.',
      'Vaso honorable, ruega por nosotros.',
      'Vaso insigne de devoción, ruega por nosotros.',
      'Rosa mística, ruega por nosotros.',
      'Torre de David, ruega por nosotros.',
      'Torre de marfil, ruega por nosotros.',
      'Casa de oro, ruega por nosotros.',
      'Arca de la alianza, ruega por nosotros.',
      'Puerta del cielo, ruega por nosotros.',
      'Estrella de la mañana, ruega por nosotros.',
      'Salud de los enfermos, ruega por nosotros.',
      'Refugio de los pecadores, ruega por nosotros.',
      'Consuelo de los afligidos, ruega por nosotros.',
      'Auxilio de los cristianos, ruega por nosotros.',
      'Reina de los ángeles, ruega por nosotros.',
      'Reina de los patriarcas, ruega por nosotros.',
      'Reina de los profetas, ruega por nosotros.',
      'Reina de los apóstoles, ruega por nosotros.',
      'Reina de los mártires, ruega por nosotros.',
      'Reina de los confesores, ruega por nosotros.',
      'Reina de las vírgenes, ruega por nosotros.',
      'Reina de todos los santos, ruega por nosotros.',
      'Reina concebida sin pecado original, ruega por nosotros.',
      'Reina asunta al cielo, ruega por nosotros.',
      'Reina del santísimo Rosario, ruega por nosotros.',
      'Reina de la paz, ruega por nosotros.',
      'Cordero de Dios, que quitas los pecados del mundo, perdónanos, Señor.',
      'Cordero de Dios, que quitas los pecados del mundo, escúchanos, Señor.',
      'Cordero de Dios, que quitas los pecados del mundo, ten piedad de nosotros.',
    ],
  };

  static const closingPrayer = {
    'en': 'V. Pray for us, O holy Mother of God.\nR. That we may be made worthy of the promises of Christ.\n\nLet us pray: O God, whose only-begotten Son, by His life, death, and resurrection, has purchased for us the rewards of eternal life; grant, we beseech Thee, that, meditating upon these mysteries of the Most Holy Rosary of the Blessed Virgin Mary, we may imitate what they contain and obtain what they promise, through the same Christ our Lord. Amen.',
    'la': 'V. Ora pro nobis, sancta Dei Génitrix.\nR. Ut digni efficiámur promissiónibus Christi.\n\nOrémus: Deus, cuius Fílius únicus, vita, morte et resurrectióne sua, nos ætérnæ vitæ præmia consecúti est; concéde, quæsumus, ut hæc sacratíssimi Rosárii Beátæ Maríæ Vírginis mystéria pie recoléntes, et imitémur quod continént, et assequámur quod promíttunt. Per eúndem Christum Dóminum nostrum. Amen.',
    'es': 'V. Ruega por nosotros, santa Madre de Dios.\nR. Para que seamos dignos de las promesas de Cristo.\n\nOremos: Oh Dios, cuyo Unigénito Hijo, con su vida, muerte y resurrección, nos ha merecido el premio de la vida eterna; concédenos, te rogamos, que meditando los misterios del santísimo Rosario de la Bienaventurada Virgen María, imitemos lo que contienen y alcancemos lo que prometen. Por el mismo Cristo nuestro Señor. Amén.',
  };

  static List<String> getInvocations(String lang) {
    return invocations[lang] ?? invocations['en']!;
  }

  static String getClosingPrayer(String lang) {
    return closingPrayer[lang] ?? closingPrayer['en']!;
  }
}