import 'package:flutter/material.dart';
import '../../config/theme.dart';

class Novena {
  final String id;
  final String title;
  final String subtitle;
  final String saintOrFeast;
  final IconData icon;
  final Color color;
  final String startDateNote;
  final List<String> dayPrayers;

  const Novena({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.saintOrFeast,
    required this.icon,
    required this.color,
    required this.startDateNote,
    required this.dayPrayers,
  });
}

final List<Novena> catholicNovenas = [
  Novena(
    id: 'divine_mercy',
    title: 'Divine Mercy Novena',
    subtitle: 'Given by Jesus to St. Faustina',
    saintOrFeast: 'Jesus — Divine Mercy',
    icon: Icons.favorite,
    color: Color(0xFFE57373),
    startDateNote: 'Begins Good Friday, ends Divine Mercy Sunday',
    dayPrayers: [
      'Day 1 — All mankind, especially sinners:\n"Today, bring to Me all mankind, especially all sinners, and immerse them in the ocean of My mercy."\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be, then the Chaplet of Divine Mercy.',
      'Day 2 — Priests and religious:\n"Today, bring to Me the souls of priests and religious, and immerse them in My unfathomable mercy."\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be, then the Chaplet of Divine Mercy.',
      'Day 3 — All devout and faithful souls:\n"Today, bring to Me all devout and faithful souls, and immerse them in the ocean of My mercy."\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be, then the Chaplet of Divine Mercy.',
      'Day 4 — Those who do not know Christ:\n"Today, bring to Me the pagans and those who do not know Me."\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be, then the Chaplet of Divine Mercy.',
      'Day 5 — Heretics and schismatics:\n"Today, bring to Me the souls of heretics and schismatics, and immerse them in the ocean of My mercy."\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be, then the Chaplet of Divine Mercy.',
      'Day 6 — The meek and humble, especially little children:\n"Today, bring to Me the meek and humble, and the souls of little children."\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be, then the Chaplet of Divine Mercy.',
      'Day 7 — Those who venerate and glorify My mercy:\n"Today, bring to Me the souls who especially venerate and glorify My mercy."\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be, then the Chaplet of Divine Mercy.',
      'Day 8 — The souls in Purgatory:\n"Today, bring to Me the souls who are in the prison of Purgatory."\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be, then the Chaplet of Divine Mercy.',
      'Day 9 — The lukewarm:\n"Today, bring to Me the souls who have become lukewarm."\n\nPray: 1 Our Father, 1 Hail Mary, 1 Glory Be, then the Chaplet of Divine Mercy.',
    ],
  ),
  Novena(
    id: 'miraculous_medal',
    title: 'Our Lady of the Miraculous Medal',
    subtitle: 'Through the intercession of the Blessed Virgin',
    saintOrFeast: 'Blessed Virgin Mary',
    icon: Icons.auto_awesome,
    color: FidelisTheme.gold,
    startDateNote: 'Anytime — 9 consecutive days',
    dayPrayers: [
      'Day 1: O Immaculate Virgin Mary, Mother of Our Lord Jesus and our Mother, we come to you with confidence. Obtain for us the graces we need most. Our Father, Hail Mary, Glory Be.',
      'Day 2: O Mary, conceived without sin, pray for us who have recourse to thee. Grant us the grace of fervent prayer. Our Father, Hail Mary, Glory Be.',
      'Day 3: O Blessed Virgin, refuge of sinners, intercede for us that we may obtain true sorrow for our sins. Our Father, Hail Mary, Glory Be.',
      'Day 4: O Mother of Mercy, through thy Miraculous Medal, grant us perseverance in good works. Our Father, Hail Mary, Glory Be.',
      'Day 5: O Immaculate Mary, obtain for us a lively faith, firm hope, and burning charity. Our Father, Hail Mary, Glory Be.',
      'Day 6: O Queen of Heaven, through thy powerful intercession, grant us the grace to live holy lives. Our Father, Hail Mary, Glory Be.',
      'Day 7: O Mary, comfort of the afflicted, bring our petitions before the throne of God. Our Father, Hail Mary, Glory Be.',
      'Day 8: O Virgin most powerful, obtain for us the grace to resist temptation and avoid sin. Our Father, Hail Mary, Glory Be.',
      'Day 9: O Immaculate Conception, we place our petitions at thy feet and trust in thy motherly care. Our Father, Hail Mary, Glory Be.',
    ],
  ),
  Novena(
    id: 'st_jude',
    title: 'St. Jude Thaddeus',
    subtitle: 'Patron of hopeless and desperate cases',
    saintOrFeast: 'St. Jude Thaddeus',
    icon: Icons.local_fire_department,
    color: Color(0xFFFF9800),
    startDateNote: 'Anytime — 9 consecutive days',
    dayPrayers: [
      'Day 1: Most holy Apostle, St. Jude, faithful servant and friend of Jesus, the Church honors and invokes you as the patron of hopeless cases. Pray that I may receive the grace of God. Our Father, Hail Mary, Glory Be.',
      'Day 2: St. Jude, apostle of hope, intercede for me in my necessities. Obtain for me the grace to trust in God\'s providence. Our Father, Hail Mary, Glory Be.',
      'Day 3: Glorious St. Jude, help me in my present and urgent petition. Grant that God\'s will be done in all things. Our Father, Hail Mary, Glory Be.',
      'Day 4: St. Jude, who suffered martyrdom for the faith, pray that I may have courage in my trials. Our Father, Hail Mary, Glory Be.',
      'Day 5: Blessed St. Jude, who labored among the lost, pray for me when I feel abandoned. Our Father, Hail Mary, Glory Be.',
      'Day 6: St. Jude, faithful witness to Christ, strengthen my faith in times of doubt. Our Father, Hail Mary, Glory Be.',
      'Day 7: Dear St. Jude, friend of Jesus, obtain for me the favor I seek if it be God\'s will. Our Father, Hail Mary, Glory Be.',
      'Day 8: St. Jude, patron of the desperate, fill my heart with hope and trust in God. Our Father, Hail Mary, Glory Be.',
      'Day 9: Most holy St. Jude, I give thanks to God for the graces obtained through your intercession. May I always praise the Lord. Our Father, Hail Mary, Glory Be.',
    ],
  ),
  Novena(
    id: 'st_joseph',
    title: 'St. Joseph',
    subtitle: 'Patron of the Universal Church, workers, and families',
    saintOrFeast: 'St. Joseph',
    icon: Icons.carpenter,
    color: Color(0xFF8D6E63),
    startDateNote: 'Anytime — traditionally March 10–18 for his feast',
    dayPrayers: [
      'Day 1: O glorious St. Joseph, foster father of Jesus and chaste spouse of the Blessed Virgin, obtain for me a lively faith. Our Father, Hail Mary, Glory Be.',
      'Day 2: O St. Joseph, model of humility, teach me to submit to God\'s will in all things. Our Father, Hail Mary, Glory Be.',
      'Day 3: O St. Joseph, mirror of patience, obtain for me the grace to bear my crosses with resignation. Our Father, Hail Mary, Glory Be.',
      'Day 4: O St. Joseph, model of obedience, help me to obey the commandments of God and His Church. Our Father, Hail Mary, Glory Be.',
      'Day 5: O St. Joseph, patron of workers, bless my labors and provide for my needs. Our Father, Hail Mary, Glory Be.',
      'Day 6: O St. Joseph, protector of the Holy Church, defend the Church from all enemies. Our Father, Hail Mary, Glory Be.',
      'Day 7: O St. Joseph, patron of a happy death, obtain for me the grace of final perseverance. Our Father, Hail Mary, Glory Be.',
      'Day 8: O St. Joseph, terror of demons, protect me from the snares of the evil one. Our Father, Hail Mary, Glory Be.',
      'Day 9: O glorious St. Joseph, I commend myself to your protection. Grant that through your intercession I may obtain the favors I seek. Our Father, Hail Mary, Glory Be.',
    ],
  ),
  Novena(
    id: 'sacred_heart',
    title: 'Sacred Heart of Jesus',
    subtitle: 'Devotion to the love of Christ',
    saintOrFeast: 'Sacred Heart of Jesus',
    icon: Icons.favorite_border,
    color: Color(0xFFE53935),
    startDateNote: 'Anytime — traditionally 9 days before First Friday',
    dayPrayers: [
      'Day 1: O Divine Heart of Jesus, burning with love for us, inflame my heart with love for Thee. Our Father, Hail Mary, Glory Be.',
      'Day 2: O Sacred Heart, source of all consolation, comfort me in my trials. Our Father, Hail Mary, Glory Be.',
      'Day 3: O Heart of Jesus, meek and humble, teach me to be gentle and humble of heart. Our Father, Hail Mary, Glory Be.',
      'Day 4: O Sacred Heart, refuge of sinners, have mercy on me. Our Father, Hail Mary, Glory Be.',
      'Day 5: O Heart of Jesus, full of goodness, grant me the grace of true contrition. Our Father, Hail Mary, Glory Be.',
      'Day 6: O Sacred Heart, treasure of all graces, enrich my soul with Thy gifts. Our Father, Hail Mary, Glory Be.',
      'Day 7: O Heart of Jesus, King and center of all hearts, reign in my heart. Our Father, Hail Mary, Glory Be.',
      'Day 8: O Sacred Heart, patient and most merciful, forgive me my sins. Our Father, Hail Mary, Glory Be.',
      'Day 9: O Divine Heart, I consecrate myself to Thee. Reign in me forever. Our Father, Hail Mary, Glory Be.',
    ],
  ),
  Novena(
    id: 'immaculate_conception',
    title: 'Immaculate Conception',
    subtitle: 'Patroness of the United States',
    saintOrFeast: 'Blessed Virgin Mary',
    icon: Icons.star,
    color: Color(0xFF42A5F5),
    startDateNote: 'Anytime — traditionally Nov 29–Dec 8',
    dayPrayers: [
      'Day 1: O Immaculate Mary, conceived without original sin, pray for us. Obtain for me the grace of purity of heart. Our Father, Hail Mary, Glory Be.',
      'Day 2: O Mary, spotless from the first moment of thy conception, help me to avoid all sin. Our Father, Hail Mary, Glory Be.',
      'Day 3: O Immaculate Virgin, thou who didst crush the head of the serpent, protect me from the attacks of the devil. Our Father, Hail Mary, Glory Be.',
      'Day 4: O Mary, full of grace, obtain for me an increase of grace in my soul. Our Father, Hail Mary, Glory Be.',
      'Day 5: O Immaculate Mother, who art the glory of the human race, help me to live a holy life. Our Father, Hail Mary, Glory Be.',
      'Day 6: O Blessed Virgin, chosen by God from all eternity, obtain for me the grace of perseverance. Our Father, Hail Mary, Glory Be.',
      'Day 7: O Immaculate Conception, shrine of the Holy Spirit, fill my heart with divine love. Our Father, Hail Mary, Glory Be.',
      'Day 8: O Mary, our advocate, present our petitions to thy Divine Son. Our Father, Hail Mary, Glory Be.',
      'Day 9: O Immaculate Virgin, we rejoice in thy glory and trust in thy intercession. Our Father, Hail Mary, Glory Be.',
    ],
  ),
  Novena(
    id: 'holy_spirit',
    title: 'Novena to the Holy Spirit',
    subtitle: 'The original novena — prayed by the Apostles',
    saintOrFeast: 'Holy Spirit',
    icon: Icons.wb_sunny,
    color: Color(0xFFFFCA28),
    startDateNote: '9 days before Pentecost (or anytime)',
    dayPrayers: [
      'Day 1 — Charity: Come, Holy Spirit, and fill my heart with the fire of divine charity. Our Father, Hail Mary, Glory Be + "Come, Holy Spirit, fill the hearts of Thy faithful, and kindle in them the fire of Thy love."',
      'Day 2 — Joy: Come, Holy Spirit, and grant me the grace of spiritual joy. Our Father, Hail Mary, Glory Be.',
      'Day 3 — Peace: Come, Holy Spirit, and grant me interior peace. Our Father, Hail Mary, Glory Be.',
      'Day 4 — Patience: Come, Holy Spirit, and grant me the virtue of patience. Our Father, Hail Mary, Glory Be.',
      'Day 5 — Generosity: Come, Holy Spirit, and make me generous in serving God. Our Father, Hail Mary, Glory Be.',
      'Day 6 — Goodness: Come, Holy Spirit, and fill my soul with Thy goodness. Our Father, Hail Mary, Glory Be.',
      'Day 7 — Mildness: Come, Holy Spirit, and make me gentle and mild like Christ. Our Father, Hail Mary, Glory Be.',
      'Day 8 — Faithfulness: Come, Holy Spirit, and make me faithful to my duties. Our Father, Hail Mary, Glory Be.',
      'Day 9 — Moderation: Come, Holy Spirit, and grant me the grace of self-control. Our Father, Hail Mary, Glory Be.',
    ],
  ),
  Novena(
    id: 'st_therese',
    title: 'St. Thérèse of Lisieux',
    subtitle: 'The Little Flower — "I will let fall a shower of roses"',
    saintOrFeast: 'St. Thérèse of the Child Jesus',
    icon: Icons.local_florist,
    color: Color(0xFFEC407A),
    startDateNote: 'Anytime — 9 consecutive days',
    dayPrayers: [
      'Day 1: O Little Flower of Jesus, who didst promise to let fall a shower of roses, obtain for me the grace of childlike trust in God. Our Father, Hail Mary, Glory Be.',
      'Day 2: O St. Thérèse, who didst walk the Little Way, teach me to do small things with great love. Our Father, Hail Mary, Glory Be.',
      'Day 3: O Little Flower, who found heaven in suffering, help me to bear my crosses joyfully. Our Father, Hail Mary, Glory Be.',
      'Day 4: O St. Thérèse, who loved the Holy Face of Jesus, obtain for me true devotion to Christ. Our Father, Hail Mary, Glory Be.',
      'Day 5: O Little Flower, doctor of the Church, obtain for me wisdom and understanding. Our Father, Hail Mary, Glory Be.',
      'Day 6: O St. Thérèse, patron of the missions, help me to spread the Gospel by my example. Our Father, Hail Mary, Glory Be.',
      'Day 7: O Little Flower, who trusted completely in God, increase my faith and hope. Our Father, Hail Mary, Glory Be.',
      'Day 8: O St. Thérèse, who prayed from your cloister for the whole world, intercede for my intentions. Our Father, Hail Mary, Glory Be.',
      'Day 9: O Little Flower, I thank God for the blessings obtained through your intercession. May I love God more each day. Our Father, Hail Mary, Glory Be.',
    ],
  ),
  Novena(
    id: 'our_lady_montserrat',
    title: 'Our Lady of Montserrat',
    subtitle: 'Dark Virgin of Catalonia, patron of Spain',
    saintOrFeast: 'Blessed Virgin Mary — Montserrat',
    icon: Icons.terrain,
    color: Color(0xFF7E57C2),
    startDateNote: 'Anytime — 9 consecutive days',
    dayPrayers: [
      'Day 1: O Our Lady of Montserrat, Mother of God and our Mother, we entrust ourselves to thee. Our Father, Hail Mary, Glory Be.',
      'Day 2: O Blessed Virgin of Montserrat, obtain for me the grace of sincere conversion of heart. Our Father, Hail Mary, Glory Be.',
      'Day 3: O Our Lady, who art seated upon the mountain of grace, lift me up to God. Our Father, Hail Mary, Glory Be.',
      'Day 4: O Dark Virgin, who shiniest with the light of Christ, illuminate my path. Our Father, Hail Mary, Glory Be.',
      'Day 5: O Mother of Montserrat, protect all who call upon thee in their needs. Our Father, Hail Mary, Glory Be.',
      'Day 6: O Blessed Virgin, who hast comforted so many pilgrims, comfort me in my difficulties. Our Father, Hail Mary, Glory Be.',
      'Day 7: O Our Lady of Montserrat, who hast inspired saints, inspire me to holiness. Our Father, Hail Mary, Glory Be.',
      'Day 8: O Mother of Mercy, through thy intercession, obtain for me the favor I seek. Our Father, Hail Mary, Glory Be.',
      'Day 9: O Our Lady of Montserrat, I give thanks for the graces received. May I ever remain devoted to thee. Our Father, Hail Mary, Glory Be.',
    ],
  ),
  Novena(
    id: 'st_anthony',
    title: 'St. Anthony of Padua',
    subtitle: 'Patron of lost items and the poor',
    saintOrFeast: 'St. Anthony of Padua',
    icon: Icons.search,
    color: Color(0xFF66BB6A),
    startDateNote: 'Anytime — 9 consecutive days (esp. Tuesdays)',
    dayPrayers: [
      'Day 1: O glorious St. Anthony, who didst preach the Gospel with power, obtain for me the grace to live my faith boldly. Our Father, Hail Mary, Glory Be.',
      'Day 2: O St. Anthony, friend of the poor, help me to be generous to those in need. Our Father, Hail Mary, Glory Be.',
      'Day 3: O St. Anthony, finder of lost things, help me to find what I have lost — both material and spiritual. Our Father, Hail Mary, Glory Be.',
      'Day 4: O St. Anthony, hammer of heretics, strengthen me in the true faith. Our Father, Hail Mary, Glory Be.',
      'Day 5: O St. Anthony, who held the Infant Jesus, obtain for me the grace of childlike love for Christ. Our Father, Hail Mary, Glory Be.',
      'Day 6: O St. Anthony, wonder-worker, intercede for me in my pressing needs. Our Father, Hail Mary, Glory Be.',
      'Day 7: O St. Anthony, patron of the oppressed, defend me against injustice. Our Father, Hail Mary, Glory Be.',
      'Day 8: O St. Anthony, who didst love the Eucharist, increase my devotion to the Blessed Sacrament. Our Father, Hail Mary, Glory Be.',
      'Day 9: O glorious St. Anthony, I thank God for the favors obtained through your intercession. May I ever imitate your virtues. Our Father, Hail Mary, Glory Be.',
    ],
  ),
  Novena(
    id: 'st_michael',
    title: 'St. Michael the Archangel',
    subtitle: 'Defender in battle, protector against evil',
    saintOrFeast: 'St. Michael the Archangel',
    icon: Icons.shield,
    color: Color(0xFF1565C0),
    startDateNote: 'Anytime — 9 consecutive days (esp. before Sept 29 feast)',
    dayPrayers: [
      "Day 1 — St. Michael, Prince of the Heavenly Host:\nO glorious St. Michael, Prince of the Heavenly Host, defend us in battle against the powers of darkness. Protect us from the snares of the devil and command him to depart. Our Father, Hail Mary, Glory Be.\n\nPrayer to St. Michael: St. Michael the Archangel, defend us in battle. Be our protection against the wickedness and snares of the devil. May God rebuke him, we humbly pray. And do thou, O Prince of the Heavenly Host, by the power of God, cast into hell Satan and all the evil spirits who prowl about the world seeking the ruin of souls. Amen.",
      "Day 2 — St. Michael, Defender of the Church:\nO St. Michael, guardian and protector of the Holy Catholic Church, intercede for her against all enemies. Obtain for us the grace to remain steadfast in the faith. Our Father, Hail Mary, Glory Be.\n\nPrayer to St. Michael: St. Michael the Archangel, defend us in battle...",
      "Day 3 — St. Michael, Champion of God's Justice:\nO St. Michael, who didst cast down Lucifer and his rebel angels by the command of God, obtain for me the grace of true humility and obedience to God's will. Our Father, Hail Mary, Glory Be.\n\nPrayer to St. Michael: St. Michael the Archangel, defend us in battle...",
      "Day 4 — St. Michael, Guardian of the Blessed Sacrament:\nO St. Michael, who dost adore the Blessed Sacrament with the angels of heaven, obtain for me an ever-deeper devotion to the Real Presence of Christ. Our Father, Hail Mary, Glory Be.\n\nPrayer to St. Michael: St. Michael the Archangel, defend us in battle...",
      "Day 5 — St. Michael, Protector of the Dying:\nO St. Michael, who art present at the hour of death to defend souls from the assaults of the devil, obtain for me the grace of a holy and peaceful death. Our Father, Hail Mary, Glory Be.\n\nPrayer to St. Michael: St. Michael the Archangel, defend us in battle...",
      "Day 6 — St. Michael, Guardian of Souls in Purgatory:\nO St. Michael, who dost assist the holy souls in Purgatory, obtain for them relief and eternal rest. May I also be purified and made worthy of heaven. Our Father, Hail Mary, Glory Be.\n\nPrayer to St. Michael: St. Michael the Archangel, defend us in battle...",
      "Day 7 — St. Michael, Guide of the Faithful:\nO St. Michael, guide of souls to the heavenly kingdom, lead me on the path of righteousness. Protect me from the deceits of the evil one. Our Father, Hail Mary, Glory Be.\n\nPrayer to St. Michael: St. Michael the Archangel, defend us in battle...",
      "Day 8 — St. Michael, Strength in Temptation:\nO St. Michael, mighty warrior of God, strengthen me in times of temptation. Shield me from all evil and help me to stand firm in virtue. Our Father, Hail Mary, Glory Be.\n\nPrayer to St. Michael: St. Michael the Archangel, defend us in battle...",
      "Day 9 — St. Michael, Victorious Leader:\nO glorious St. Michael, who didst triumph over the powers of hell, obtain for me final perseverance and the grace to fight valiantly against all evil. May I, with thee, be found worthy to enter the glory of heaven. Our Father, Hail Mary, Glory Be.\n\nPrayer to St. Michael: St. Michael the Archangel, defend us in battle. Be our protection against the wickedness and snares of the devil. May God rebuke him, we humbly pray. And do thou, O Prince of the Heavenly Host, by the power of God, cast into hell Satan and all the evil spirits who prowl about the world seeking the ruin of souls. Amen.",
    ],
  ),
];